### ISSUE TITLE
Content is Cut Off on Mobile

### ISSUE THREAD

**Issue by cpastre1** [TaxFoundation/tf-web-styles#48]
Content on mobile is wider than viewport. The mobile menu icon is also not scaling properly.

![2016-07-15 11_43_59-tax foundation style guide](https://cloud.githubusercontent.com/assets/10962539/16880096/9aa99090-4a81-11e6-9ae8-d7b71660805f.png)

**Comment by tvanantwerp** [comment]
Looks like the main problem is images not shrinking. I'll add some styles to fix this.
